### ISSUE TITLE
Banned Mobs still Occasionally Spawning

### ISSUE THREAD

**Issue by bloodconfetti** [Darkhax-Minecraft/BadMobs#18]
`#General settings for the mod.
[general]
	#A list of all banned mobs. If a mobs entity id is added to this list, it will not be allowed to spawn in any world.
	bannedMobs = ["minecraft:blaze", "minecraft:phantom", "minecraft:pillager", "minecraft:cave_spider", "minecraft:silverfish", "minecraft:creeper", "minecraft:ravager", "minecraft:drowned", "minecraft:shulker", "minecraft:elder_guardian", "minecraft:ender_dragon", "minecraft:endermite", "minecraft:enderman", "minecraft:evocation_illager", "minecraft:skeleton", "minecraft:skeleton_horse", "minecraft:spider", "minecraft:stray", "minecraft:ghast", "minecraft:giant", "minecraft:guardian", "minecraft:wither", "minecraft:husk", "minecraft:vex", "minecraft:vindication_illager", "minecraft:witch", "minecraft:wither_skeleton", "minecraft:magma_cube", "minecraft:zombie", "minecraft:zombie_villager"]

#Client only settings.
[client]
	#Displays the ID of mobs on their spawn egg tooltip while enabled.
	addTooltip = false`

Hey there, this is my config setup for mod version: BadMobs-1.14.4-3.0.1, Forge 28.0.45, and Minecraft 1.14.4

There were still a couple of skeletons at a spawner I found, and then I heard a couple of zombies but did not see them, but the mob that seems the most persistent are the Drowned.

**Comment by AltPlus30** [comment]
Same here.
**Config:**
```
#General settings for the mod.
[general]
	#A list of all banned mobs. If a mobs entity id is added to this list, it will not be allowed to spawn in any world.
	bannedMobs = ["minecraft:spider", "minecraft:ghast"]

#Client only settings.
[client]
	#Displays the ID of mobs on their spawn egg tooltip while enabled.
	addTooltip = true
```
**These guys still spawn in my world.**
Version of mod: _BadMobs-1.14.4-3.0.1_
Version of Forge: _28.0.45_
Version of MC: _1.14.4_

**Comment by josephpontin** [comment]
And me.
```
#General settings for the mod.
[general]
	#A list of all banned mobs. If a mobs entity id is added to this list, it will not be allowed to spawn in any world.
	bannedMobs = ["minecraft:spider"]

#Client only settings.
[client]
	#Displays the ID of mobs on their spawn egg tooltip while enabled.
	addTooltip = true
```

Spiders continue to spawn both naturally and by spawn egg.

Running same versions of game, Forge and the mod as above.

**Comment by Darkhax** [comment]
The mod specifically doesn't prevent spawners and spawn eggs from working. It just removes the ability for mobs to naturally spawn.

**Comment by AltPlus30** [comment]
> The mod specifically **doesn't prevent spawners and spawn eggs from working**. It just removes the ability for mobs to naturally spawn.
>
In the F.A.Q. section you said that 
> Yes, this will prevent mobs from spawning, even if they are spawned from a block structure, **Mob Spawner**, or **Spawn Egg**.
>

**Comment by bloodconfetti** [comment]
I personally am rather happy if there's an option to let them spawn from eggs, since clearly the user is deciding they *want* the mob to exist if they're throwing an egg.

**Comment by Darkhax** [comment]
It looks like the CurseForge page has not been updated to reflect the changes in 1.13+ and still references the older information. For example, dimension specific removal is also no longer available. I am guessing there was some bug on Curse's end, or maybe I didn't save, because I did rewrite the mod post to explain how things have changed.

In 1.12 and below the mod would remove mobs from all sources, including existing mobs. This behaviour was replaced with the natural spawn only behaviour to improve performance of the mod on servers and to simplify the mod's code. 1.12 also had the "aggressive removal" option which would re-enable the old behaviour however this option was only there so existing users of the mod would not run into issues. 

In 1.13+ they changed the spawning system to introduce spawn reason information. This system is somewhat different from previous versions of the game. However it does potentially allow for specific control over different spawn types. I would like to introduce this as a replacement for the old agressive removal system from 1.12. This would also likely include the dimension specific stuff again as well.

Here is a list of all the spawn reasons that could potentially be supported. NATURAL, CHUNK_GENERATION, SPAWNER, STRUCTURE, BREEDING, MOB_SUMMONED, JOCKEY, EVENT, CONVERSION, REINFORCEMENT, TRIGGERED, BUCKET, SPAWN_EGG, COMMAND,  DISPENSER, PATROL;

**Comment by AltPlus30** [comment]
> Here is a list of all the spawn reasons that could potentially be supported. NATURAL, CHUNK_GENERATION, SPAWNER, STRUCTURE, BREEDING, MOB_SUMMONED, JOCKEY, EVENT, CONVERSION, REINFORCEMENT, TRIGGERED, BUCKET, SPAWN_EGG, COMMAND, DISPENSER, PATROL;
>
So, does this mean there will be an update on this mod anytime soon?

**Comment by Darkhax** [comment]
@AltPlus30 It depends on whether or not Forge will allow modders to access that information. It is currently not possible with what Forge offers now. I've created a feature request for this.

**Comment by Darkhax** [comment]
This feature was added in Forge earlier this month. A new update which adds support for this will be released when I get a chance to code it. https://github.com/MinecraftForge/MinecraftForge/pull/6096

**Comment by Darkhax** [comment]
Additional restrictions are now handled. There are config options to turn spawners and spawn eggs off.
