### ISSUE TITLE
[Suggestion] Rather than stop a type of spawn. Limit the amount of it that can exist.

### ISSUE THREAD

**Issue by Darkmega18** [Darkhax-Minecraft/BadMobs#62]
Something that would be useful for packs with a wide variety of mobs that spawn.

The ability to set a maximum number of a type of natural mob spawns that can exist in someones spawnable area.

For example limiting mutant bosses to 1 or so. or reducing zombies, creepers skellies etc from normal night/darkness spawns down to like 10-15 a piece so more unique things with lower weights can attempt spawns with the left over cap like quarks special underground undeads or dungeon gear's mobs.

**Comment by Darkhax** [comment]
Thanks for the feature request. While this wouldn't be that challenging to implement it is very out of scope for this mod. Bad Mobs is meant to be a simple mod that non-technical players can throw in to remove things they dislike from the game rather than being a complex pack tool that can be used to replace the vanilla spawning system.

I would recommend looking in to McJty's [In Control](https://www.curseforge.com/minecraft/mc-mods/in-control) mod which provides much deeper granularity in modifying mob spawning.

**Comment by Darkmega18** [comment]
Ah yep. I figured this would be the case. Thanks anyways.
