### ISSUE TITLE
Popping sound near beehive

### ISSUE THREAD

**Issue by Mitch98k** [Darkhax-Minecraft/BadMobs#69]
I have disabled the spawning of bees with this mod, but I've noticed that anytime I get near a beehive there is this popping sound that plays. It seems to grow more intense the closer I get to the hive, and the sound is coming directly from the hive.

**Comment by Darkhax** [comment]
This is because the bee is trying to escape the hive and you are using this mod to prevent that. The vanilla code here plays the sound before it even tries to spawn the bee and would be classified as a vanilla bug. I could use mixins to rewrite how beehives work but that is out of scope for what this mod should be doing.
