### ISSUE TITLE
Beehive constant popping sound

### ISSUE THREAD

**Issue by Deaymon** [Darkhax-Minecraft/BadMobs#74]
Minecraft 1.19.2
With bee spawning disabled, whenever I get close enough to a naturally generated beehive, it makes the 'POP' sound of a bee getting out of it, but constantly, like 20 times per second or something.
It's uncomfortably loud, and the only way to get rid of it seems to be breaking the beehive.

**Comment by Draylynn** [comment]
This may be related, but similar problems.
1.19.2 - 16.1.3; added to FTB:Skies, the mobs I disabled for natural spawning (Whirlisprig/Drygmy/Starbuncle - Ars Nouveau) and spawner spawning, still spawned, but were invisible... Could still hear them walking around and walking into spikes etc and dying.

**Comment by Darkhax** [comment]
> Minecraft 1.19.2
With bee spawning disabled, whenever I get close enough to a naturally generated beehive, it makes the 'POP' sound of a bee getting out of it, but constantly, like 20 times per second or something.
It's uncomfortably loud, and the only way to get rid of it seems to be breaking the beehive.

This is an issue with how Forge chose to implement their mob spawning API. The bee is removed from the world but not the hive so it keeps trying to spawn more. Unfortunately this is not something I can fix.

>This may be related, but similar problems.
1.19.2 - 16.1.3; added to FTB:Skies, the mobs I disabled for natural spawning (Whirlisprig/Drygmy/Starbuncle - Ars Nouveau) and spawner spawning, still spawned, but were invisible... Could still hear them walking around and walking into spikes etc and dying.

This issue is caused by installing the mod on the client but not the server. If you are playing on a server you need to install the mod AND configure it to prevent the spawning on the server.
