### ISSUE TITLE
Mobs appear invisible on server even when configs are identical [1.18.2]

### ISSUE THREAD

**Issue by GoldenMaster8** [Darkhax-Minecraft/BadMobs#76]
I am currently running a server using this mod and the mobs that are disabled can still attack but are invisible. I looked into other issues like it and found issue #64 , I then made sure the configs were identical, in which they are, but when I reload the server to put the config into effect, not only does it not work, but it also seems to create new files called "badmobs-common-(a number, 1-4).bak" is there any fix to this or is this a new problem

**Comment by Darkhax** [comment]
You need to restart the server for changes to take effect, a simple reload will not work. The `.bak` files you are seeing are generated by Forge when the user defined config is invalid, this means that the default config with nothing disabled is being loaded on the server instead of the config you uploaded.

**Comment by GoldenMaster8** [comment]
If I change the .bak files will the config then work?
