### ISSUE TITLE
Disabling Natural mob spawning disables mob spawning via eggs and commands as well.

### ISSUE THREAD

**Issue by Itssteve1** [Darkhax-Minecraft/BadMobs#77]
Whenever you turn off natural spawning for a particular mob is disables all varieties of spawning.

**Comment by Darkhax** [comment]
It's a known issue in 1.19.3 and below that disabling normal spawning will also disable spawners and spawn eggs. It's related to a bug in the Forge API where the spawn type information is unreliably given to mods. This was fixed in 1.19.4 but required breaking changes and will not be backported to older versions.
